### PR TITLE
Update for Coop Intro

### PR DESCRIPTION
**Pull request by WhyANameWhy**

### CODE REVIEW

**Comment by Skinz3** [comment]
Declined. We must keep coop  intermediate mode playable.

**Comment by Skinz3** [comment]
what is the advantage of the intro mode? 
Do you know about experience gain difference?

**Comment by WhyANameWhy** [comment]
I keep coop and startCoop this are additional file.
You get the same experience in all Coop modes but in intro are only other bots. When you play in intermediate there are other players who can you see that you are a bot and report you. In intro like I said are all most times all bots.

**Comment by WhyANameWhy** [comment]
Here is the the reference I used for experience: https://leagueoflegends.fandom.com/wiki/Experience_%28summoner%29

**Comment by WhyANameWhy** [comment]
I see that I did a mistake I wanted to edit startCoop Intro sorry for everything

**Pull request closed without merging**
