### PR TITLE
Random champion selection

### PR DESCRIPTION
**Pull request by 53jk1**
To avoid the chance of being banned, I created a system that looks for a random name from the pool of champion names. In the lobby, boot chooses one of the random champion inputed before.

### CODE REVIEW

**Comment by 53jk1** [comment]
This will be more difficult to detect for the anti-bot system.

**Comment by LucasRKrueger** [comment]
I get your point but, playing with one champion doesn't mean that u're a bot.

**Comment by Skinz3** [comment]
> 
> 
> I don't think that it's a necessary change,
> using a fixed champion is better, because
> most times you won't have that random champion

Approved. Sorry , pull request declined.

**Comment by 53jk1** [comment]
But user can code names of the champions, and then he will roll.

**Comment by 53jk1** [comment]
For example X have Ashe, Miss Fortune and Amumu, then he's coding 3 random champions. If he wants to he can add some more

**Comment by 53jk1** [comment]
The only way to fucc up is to bad set random champions

**Pull request closed without merging**
